# Generated by Django 2.0.2 on 2018-10-24 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('plan', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=45, null=True)),
                ('email', models.CharField(max_length=45, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='participant',
            field=models.ManyToManyField(related_name='member', to='trip_buddy.User'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='trip_buddy.User'),
        ),
    ]
